import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import QueryProviders from "@/components/providers/query-provider";
import { Toaster } from "@/components/ui/toaster";

import UploadBookModal from "@/features/books/components/upload-book-modal";
import BookReaderModal from "@/features/books/components/book-reader-modal";

import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ReaderProvider } from "@/context/reader-context";
import { Metadata } from "next";
import { cn } from "@/lib/utils";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(`${inter.className} antialiased`)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ReaderProvider>
            <QueryProviders>
              <NuqsAdapter>
                <UploadBookModal />
                <BookReaderModal />
                <Toaster />
                {children}
              </NuqsAdapter>
            </QueryProviders>
          </ReaderProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
