import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Inter } from "next/font/google";
import { Metadata } from "next";

import { cn } from "@/lib/utils";

import AnnotaionModal from "@/features/annotations/components/annotations-modal";
import UploadBookModal from "@/features/books/components/upload-book-modal";
import BookReaderModal from "@/features/books/components/book-reader-modal";

import { ThemeProvider } from "@/components/providers/theme-provider";
import QueryProviders from "@/components/providers/query-provider";
import { Toaster } from "@/components/ui/toaster";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(`${inter.className} antialiased`)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProviders>
            <NuqsAdapter>
              <main>{children}</main>
            </NuqsAdapter>
            <Toaster />
          </QueryProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
